// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpmdofcvvgbtunttdeea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwbWRvZmN2dmdidHVudHRkZWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTg3MDAsImV4cCI6MjA2NDU5NDcwMH0.8sG1EeegXKD2kUUfrqvEF-fBpHEEwkhj7uFouhzm4QE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);